syntax = "proto3";

option csharp_namespace = "Promotion.GRPS.Protos";

service PromotionService {
  rpc GetPromotion (GetPromotionRequest) returns (PromotionResponse);
  rpc CreatePromotion (CreatePromotionRequest) returns (CreatePromotionResponse);
}

message GetPromotionRequest {
  string catalog_item_id = 1;
}

message PromotionResponse {
  string id = 1;
  string catalog_item_id = 2;
  string title = 3;
  double value = 4;
}

message CreatePromotionRequest {
  string catalog_item_id = 1;
  string title = 2;
  double value = 3;
}

message CreatePromotionResponse {
  string id = 1;
}