version: '3.8'
name: eshopflow-backend
services:
  
  catalog_db:
    container_name: catalog-db
    image: postgres:18.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME_CATALOG}
    restart: always
    ports:
      - "${POSTGRES_PORT_CATALOG}:5432"
    volumes:
      - postgres_catalog_prod:/var/lib/postgresql/data/
    networks:
      - eshop-network

  basket_db:
    container_name: basket-db
    image: postgres:18.0
    environment :
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME_BASKET}
    restart: always
    ports:
      - "${POSTGRES_PORT_BASKET}:5432"
    volumes:
      - postgres_basket_prod:/var/lib/postgresql/data/
    networks:
      - eshop-network

  promotion_db:
    container_name: promotion-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME_PROMOTION}
    restart: always
    ports:
      - "${MYSQL_PORT_PROMOTION}:3306"
    volumes:
      - mysql_promotion:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345678" ]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - eshop-network

  basket_redis:
    container_name: basket-redis
    image: redis:8.2.0
    command: redis-server --requirepass "${REDIS_PASSWORD}" --protected-mode no
    restart: always
    ports:
      - "${REDIS_PORT_BASKET}:6379"
    volumes:
      - redis_basket_prod:/data
    networks:
      - eshop-network

  catalog_api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "7301:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PgConnection=${PG_CONNECTION_CATALOG}
    depends_on:
      catalog_db:
        condition: service_started
    restart: unless-stopped
    networks:
      - eshop-network

  basket_api:
    container_name: basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "7302:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PgConnection=${PG_CONNECTION_BASKET}
      - ConnectionStrings__RedisConnection=${REDIS_CONNECTION_BASKET}
    depends_on:
      basket_db:
        condition: service_started
      basket_redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - eshop-network

  promotion_api:
    container_name: promotion.grps
    build:
      context: .
      dockerfile: src/Services/Promotion/Promotion.GRPS/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "7303:8080"
      - "7313:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MySqlConnection=${MYSQL_CONNECTION_PROMOTION}
    depends_on:
      promotion_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - eshop-network

volumes:
  postgres_catalog_prod:
  postgres_basket_prod:
  mysql_promotion:
  redis_basket_prod:
    
networks:
  eshop-network:
    driver: bridge