version: '3.8'
name: eshopflow-backend
services:
  
  catalog_db:
    container_name: catalog-db-dev
    image: postgres:18.0
    environment :
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_NAME_CATALOG}
    restart: always
    ports:
      - "${POSTGRES_PORT_CATALOG}:5432"
    volumes:
      - postgres_catalog:/var/tib/postgresql/data/
    networks:
      - eshop-network

  basket_db:
    container_name: basket-db-dev
    image: postgres:18.0
    environment :
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME_BASKET}
    restart: always
    ports:
      - "${POSTGRES_PORT_BASKET}:5432"
    volumes:
      - postgres_basket:/var/tib/postgresql/data/
    networks:
      - eshop-network
      
  basket_redis:
    container_name: basket-redis-dev
    image: redis:8.2.0
    command: redis-server --requirepass "${REDIS_PASSWORD}" --protected-mode no
    restart: always
    ports:
      - "${REDIS_PORT_BASKET}:6379"
    volumes:
      - redis_basket:/data
    networks:
      - eshop-network

volumes:
  postgres_catalog:
  postgres_basket:
  redis_basket:
    
networks:
  eshop-network:
    driver: bridge